version: '3'

services:
 xserver:
  image: ${REPOSITORY}xserver
  ports:
  - "8080:8080"

 rtiexec:
  image: ${REPOSITORY}vtmak-rtiexec:${VTMAK_VERSION}
  environment:
  - DISPLAY=${DISPLAY}
  ports:
  - "4000:4000"
  - "5000:5000"
  - "9001:9001"
